### ISSUE TITLE
ITKApproximateSignedDistanceMapImage Test fails

### ISSUE THREAD

**Issue by imikejackson** [BlueQuartzSoftware/ITKImageProcessing#148] opened 2017-09-28 15:29 UTC
The test fails due to differences in the filter between ITK 4.11 and 4.12

**Comment by imikejackson** [comment] 2017-09-28 16:28
![screen shot 2017-09-28 at 11 22 50 am](https://user-images.githubusercontent.com/5182396/30978430-8318c24e-a448-11e7-846e-340c511d451d.png)

**Comment by fbudin69500** [comment] 2017-10-30 20:21
@imikejackson Could you let me know the configuration of the machine on which this test fails? I cannot reproduce it locally.

**Comment by imikejackson** [comment] 2017-10-30 23:13
Hmm, Now it seems to be working? the different was between ITK 4.11 and 4.12 on all platforms. But now it seems that everything is passing? Odd.

**Comment by fbudin69500** [comment] 2017-10-31 21:00
Odd indeed. Closing this issue for now then.

**Closed as completed by fbudin69500** 2017-10-31 21:00 UTC
Labels: bug
